development:
  host: localhost
  database: invitation_development

test:
  host: localhost
  database: invitation_test

# set these environment variables on your prod server
production:
  host: localhost
  database: invitation_product
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
